// <auto-generated />
using System;
using CanvasPhase3.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CanvasPhase3.Entities
{
    [DbContext(typeof(LMSContext))]
    [Migration("20260717200300_InitialSetupMod1")]
    partial class InitialSetupMod1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Administrator", b =>
                {
                    b.Property<string>("Uid")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("uid");

                    b.HasKey("Uid")
                        .HasName("administrators_pkey");

                    b.ToTable("administrators", (string)null);
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Assignment", b =>
                {
                    b.Property<int>("Assignmentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("assignmentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Assignmentid"));

                    b.Property<int>("Categoryid")
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("Duedate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("duedate");

                    b.Property<int?>("Maxscore")
                        .HasColumnType("integer")
                        .HasColumnName("maxscore");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("Assignmentid", "Categoryid")
                        .HasName("assignments_pkey");

                    b.HasIndex("Categoryid");

                    b.HasIndex(new[] { "Assignmentid" }, "unique_assignmentid")
                        .IsUnique();

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Assignmentcategory", b =>
                {
                    b.Property<int>("Categoryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Categoryid"));

                    b.Property<int>("Classid")
                        .HasColumnType("integer")
                        .HasColumnName("classid");

                    b.Property<short?>("Gradingweight")
                        .HasColumnType("smallint")
                        .HasColumnName("gradingweight");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Categoryid", "Classid")
                        .HasName("assignmentcategories_pkey");

                    b.HasIndex("Classid");

                    b.HasIndex(new[] { "Categoryid" }, "assignmentcategories_categoryid_key")
                        .IsUnique();

                    b.ToTable("assignmentcategories", (string)null);
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Assignmentsubmission", b =>
                {
                    b.Property<DateTime>("Submissiontime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("submissiontime");

                    b.Property<string>("Studentid")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("studentid");

                    b.Property<int>("Assignmentid")
                        .HasColumnType("integer")
                        .HasColumnName("assignmentid");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("Submissiontime", "Studentid", "Assignmentid")
                        .HasName("assignmentsubmissions_pkey");

                    b.HasIndex("Assignmentid");

                    b.HasIndex("Studentid");

                    b.ToTable("assignmentsubmissions", (string)null);
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Class", b =>
                {
                    b.Property<int>("Classid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("classid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Classid"));

                    b.Property<string>("Catalogid")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("catalogid");

                    b.Property<TimeOnly?>("Endtime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("endtime");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location");

                    b.Property<string>("Profid")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("profid");

                    b.Property<string>("Semesterterm")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("semesterterm");

                    b.Property<short?>("Semesteryear")
                        .HasColumnType("smallint")
                        .HasColumnName("semesteryear");

                    b.Property<TimeOnly?>("Starttime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("starttime");

                    b.HasKey("Classid", "Catalogid")
                        .HasName("classes_pkey");

                    b.HasIndex("Catalogid");

                    b.HasIndex("Profid");

                    b.HasIndex(new[] { "Classid" }, "unique_classid")
                        .IsUnique();

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Course", b =>
                {
                    b.Property<string>("Catalogid")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("catalogid");

                    b.Property<int?>("Depid")
                        .HasColumnType("integer")
                        .HasColumnName("depid");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<short?>("Number")
                        .HasColumnType("smallint")
                        .HasColumnName("number");

                    b.HasKey("Catalogid")
                        .HasName("courses_pkey");

                    b.HasIndex("Depid");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Department", b =>
                {
                    b.Property<int>("Depid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("depid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Depid"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Subjabbrv")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("subjabbrv");

                    b.HasKey("Depid")
                        .HasName("departments_pkey");

                    b.HasIndex(new[] { "Subjabbrv" }, "departments_subjabbrv_key")
                        .IsUnique();

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Enrollment", b =>
                {
                    b.Property<int>("Classid")
                        .HasColumnType("integer")
                        .HasColumnName("classid");

                    b.Property<string>("Uid")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("uid");

                    b.Property<string>("Grade")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("grade");

                    b.HasKey("Classid", "Uid")
                        .HasName("enrollment_pkey");

                    b.HasIndex("Uid");

                    b.ToTable("enrollment", (string)null);
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Professor", b =>
                {
                    b.Property<string>("Uid")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("uid");

                    b.Property<int?>("Employerdep")
                        .HasColumnType("integer")
                        .HasColumnName("employerdep");

                    b.HasKey("Uid")
                        .HasName("professors_pkey");

                    b.HasIndex("Employerdep");

                    b.ToTable("professors", (string)null);
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Student", b =>
                {
                    b.Property<string>("Uid")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("uid");

                    b.Property<int?>("Majordep")
                        .HasColumnType("integer")
                        .HasColumnName("majordep");

                    b.HasKey("Uid")
                        .HasName("students_pkey");

                    b.HasIndex("Majordep");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.User", b =>
                {
                    b.Property<string>("Uid")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName(" uid");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date")
                        .HasColumnName(" dob");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName(" firstname");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName(" lastname");

                    b.HasKey("Uid")
                        .HasName("users_pkey");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Assignment", b =>
                {
                    b.HasOne("CanvasPhase3.CanvasPhase3.Entities.Assignmentcategory", "Category")
                        .WithMany("Assignments")
                        .HasForeignKey("Categoryid")
                        .HasPrincipalKey("Categoryid")
                        .IsRequired()
                        .HasConstraintName("assignments_categoryid_fkey");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Assignmentcategory", b =>
                {
                    b.HasOne("CanvasPhase3.CanvasPhase3.Entities.Class", "Class")
                        .WithMany("Assignmentcategories")
                        .HasForeignKey("Classid")
                        .HasPrincipalKey("Classid")
                        .IsRequired()
                        .HasConstraintName("assignmentcategories_classid_fkey");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Assignmentsubmission", b =>
                {
                    b.HasOne("CanvasPhase3.CanvasPhase3.Entities.Assignment", "Assignment")
                        .WithMany("Assignmentsubmissions")
                        .HasForeignKey("Assignmentid")
                        .HasPrincipalKey("Assignmentid")
                        .IsRequired()
                        .HasConstraintName("assignmentsubmissions_assignmentid_fkey");

                    b.HasOne("CanvasPhase3.CanvasPhase3.Entities.Student", "Student")
                        .WithMany("Assignmentsubmissions")
                        .HasForeignKey("Studentid")
                        .IsRequired()
                        .HasConstraintName("assignmentsubmissions_studentid_fkey");

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Class", b =>
                {
                    b.HasOne("CanvasPhase3.CanvasPhase3.Entities.Course", "Catalog")
                        .WithMany("Classes")
                        .HasForeignKey("Catalogid")
                        .IsRequired()
                        .HasConstraintName("classes_catalogid_fkey");

                    b.HasOne("CanvasPhase3.CanvasPhase3.Entities.Professor", "Prof")
                        .WithMany("Classes")
                        .HasForeignKey("Profid")
                        .HasConstraintName("classes_profid_fkey");

                    b.Navigation("Catalog");

                    b.Navigation("Prof");
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Course", b =>
                {
                    b.HasOne("CanvasPhase3.CanvasPhase3.Entities.Department", "Dep")
                        .WithMany("Courses")
                        .HasForeignKey("Depid")
                        .HasConstraintName("courses_depid_fkey");

                    b.Navigation("Dep");
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Enrollment", b =>
                {
                    b.HasOne("CanvasPhase3.CanvasPhase3.Entities.Class", "Class")
                        .WithMany("Enrollments")
                        .HasForeignKey("Classid")
                        .HasPrincipalKey("Classid")
                        .IsRequired()
                        .HasConstraintName("enrollment_classid_fkey");

                    b.HasOne("CanvasPhase3.CanvasPhase3.Entities.Student", "UidNavigation")
                        .WithMany("Enrollments")
                        .HasForeignKey("Uid")
                        .IsRequired()
                        .HasConstraintName("enrollment_uid_fkey");

                    b.Navigation("Class");

                    b.Navigation("UidNavigation");
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Professor", b =>
                {
                    b.HasOne("CanvasPhase3.CanvasPhase3.Entities.Department", "EmployerdepNavigation")
                        .WithMany("Professors")
                        .HasForeignKey("Employerdep")
                        .HasConstraintName("professors_employerdep_fkey");

                    b.Navigation("EmployerdepNavigation");
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Student", b =>
                {
                    b.HasOne("CanvasPhase3.CanvasPhase3.Entities.Department", "MajordepNavigation")
                        .WithMany("Students")
                        .HasForeignKey("Majordep")
                        .HasConstraintName("students_majordep_fkey");

                    b.Navigation("MajordepNavigation");
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Assignment", b =>
                {
                    b.Navigation("Assignmentsubmissions");
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Assignmentcategory", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Class", b =>
                {
                    b.Navigation("Assignmentcategories");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Course", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Professors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Professor", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("CanvasPhase3.CanvasPhase3.Entities.Student", b =>
                {
                    b.Navigation("Assignmentsubmissions");

                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
